<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->insert(
            [
                ['id' => 1, 'region_id' => 1, 'name' => 'Adansi Asokwa', 'capital' => 'Adansi Asokwa', 'district_type' => 'district'],
                ['id' => 2, 'region_id' => 1, 'name' => 'Adansi North', 'capital' => 'Fomena', 'district_type' => 'district'],
                ['id' => 3, 'region_id' => 1, 'name' => 'Adansi South', 'capital' => 'New Edubiase', 'district_type' => 'district'],
                ['id' => 4, 'region_id' => 1, 'name' => 'Afigya Kwabre North', 'capital' => 'Boamang', 'district_type' => 'district'],
                ['id' => 5, 'region_id' => 1, 'name' => 'Afigya Kwabre South', 'capital' => 'Kodie', 'district_type' => 'district'],
                ['id' => 6, 'region_id' => 1, 'name' => 'Ahafo Ano North Municipal', 'capital' => 'Tepa', 'district_type' => 'municipal'],
                ['id' => 7, 'region_id' => 1, 'name' => 'Ahafo Ano South East', 'capital' => 'Adugyama', 'district_type' => 'district'],
                ['id' => 8, 'region_id' => 1, 'name' => 'Ahafo Ano South West', 'capital' => 'Mankranso', 'district_type' => 'district'],
                ['id' => 9, 'region_id' => 1, 'name' => 'Akrofuom', 'capital' => 'Akrofuom', 'district_type' => 'district'],
                ['id' => 10, 'region_id' => 1, 'name' => 'Amansie Central', 'capital' => 'Jacobu', 'district_type' => 'district'],
                ['id' => 11, 'region_id' => 1, 'name' => 'Amansie West 	Manso', 'capital' => 'Nkwanta', 'district_type' => 'district'],
                ['id' => 12, 'region_id' => 1, 'name' => 'Amansie South', 'capital' => 'Manso Adubia', 'district_type' => 'district'],
                ['id' => 13, 'region_id' => 1, 'name' => 'Asante Akim Central Municipal', 'capital' => 'Konongo', 'district_type' => 'municipal'],
                ['id' => 14, 'region_id' => 1, 'name' => 'Asante Akim North', 'capital' => 'Agogo', 'district_type' => 'district'],
                ['id' => 15, 'region_id' => 1, 'name' => 'Asante Akim South Municipal', 'capital' => 'Juaso', 'district_type' => 'municipal'],
                ['id' => 16, 'region_id' => 1, 'name' => 'Asokore Mampong Municipal', 'capital' => 'Asokore Mampong', 'district_type' => 'municipal'],
                ['id' => 17, 'region_id' => 1, 'name' => 'Asokwa Municipal', 'capital' => 'Asokwa', 'district_type' => 'municipal'],
                ['id' => 18, 'region_id' => 1, 'name' => 'Atwima Kwanwoma', 'capital' => 'Twedie', 'district_type' => 'district'],
                ['id' => 19, 'region_id' => 1, 'name' => 'Atwima Mponua', 'capital' => 'Nyinahin', 'district_type' => 'district'],
                ['id' => 20, 'region_id' => 1, 'name' => 'Atwima Nwabiagya 	Municipal', 'capital' => 'Nkawie', 'district_type' => 'municipal'],
                ['id' => 21, 'region_id' => 1, 'name' => 'Atwima Nwabiagya North', 'capital' => 'Barekese', 'district_type' => 'district'],
                ['id' => 22, 'region_id' => 1, 'name' => 'Bekwai Municipal', 'capital' => 'Bekwai', 'district_type' => 'municipal'],
                ['id' => 23, 'region_id' => 1, 'name' => 'Bosome Freho', 'capital' => 'Asiwa', 'district_type' => 'district'],
                ['id' => 24, 'region_id' => 1, 'name' => 'Bosomtwe', 'capital' => 'Kuntanase', 'district_type' => 'district'],
                ['id' => 25, 'region_id' => 1, 'name' => 'Ejisu Municipal', 'capital' => 'Ejisu', 'district_type' => 'municipal'],
                ['id' => 26, 'region_id' => 1, 'name' => 'Ejura Sekyedumase Municipal', 'capital' => 'Ejura', 'district_type' => 'municipal'],
                ['id' => 27, 'region_id' => 1, 'name' => 'Juaben Municipal', 'capital' => 'Juaben', 'district_type' => 'municipal'],
                ['id' => 28, 'region_id' => 1, 'name' => 'Kumasi Metropolitan', 'capital' => 'Kumasi', 'district_type' => 'metropolitan'],
                ['id' => 29, 'region_id' => 1, 'name' => 'Kwabre East Municipal', 'capital' => 'Mamponteng', 'district_type' => 'municipal'],
                ['id' => 30, 'region_id' => 1, 'name' => 'Kwadaso Municipal', 'capital' => 'Kwadaso', 'district_type' => 'municipal'],
                ['id' => 31, 'region_id' => 1, 'name' => 'Mampong Municipal', 'capital' => 'Mampong', 'district_type' => 'municipal'],
                ['id' => 32, 'region_id' => 1, 'name' => 'Obuasi East Municipal', 'capital' => 'Tutuka', 'district_type' => 'municipal'],
                ['id' => 33, 'region_id' => 1, 'name' => 'Obuasi Municipal', 'capital' => 'Obuasi', 'district_type' => 'municipal'],
                ['id' => 34, 'region_id' => 1, 'name' => 'Offinso Municipal', 'capital' => 'Offinso', 'district_type' => 'municipal'],
                ['id' => 35, 'region_id' => 1, 'name' => 'Offinso North', 'capital' => 'Akomadan', 'district_type' => 'district'],
                ['id' => 36, 'region_id' => 1, 'name' => 'Oforikrom Municipal', 'capital' => 'Oforikrom', 'district_type' => 'municipal'],
                ['id' => 37, 'region_id' => 1, 'name' => 'Old Tafo Municipal', 'capital' => 'Old Tafo', 'district_type' => 'municipal'],
                ['id' => 38, 'region_id' => 1, 'name' => 'Sekyere Afram Plains', 'capital' => 'Drobonso', 'district_type' => 'district'],
                ['id' => 39, 'region_id' => 1, 'name' => 'Sekyere Central', 'capital' => 'Nsuta', 'district_type' => 'district'],
                ['id' => 40, 'region_id' => 1, 'name' => 'Sekyere East', 'capital' => 'Effiduase', 'district_type' => 'district'],
                ['id' => 41, 'region_id' => 1, 'name' => 'Sekyere Kumawu', 'capital' => 'Kumawu', 'district_type' => 'district'],
                ['id' => 42, 'region_id' => 1, 'name' => 'Sekyere South', 'capital' => 'Agona', 'district_type' => 'district'],
                ['id' => 43, 'region_id' => 1, 'name' => 'Suame Municipal', 'capital' => 'Suame', 'district_type' => 'municipal'],
                ['id' => 44, 'region_id' => 2, 'name' => 'Ablekuma Central Municipal', 'capital' => 'Lartebiokorshie', 'district_type' => 'municipal'],
                ['id' => 45, 'region_id' => 2, 'name' => 'Ablekuma North Municipal', 'capital' => 'Darkuman', 'district_type' => 'municipal'],
                ['id' => 46, 'region_id' => 2, 'name' => 'Ablekuma West Municipal', 'capital' => 'Dansoman', 'district_type' => 'municipal'],
                ['id' => 47, 'region_id' => 2, 'name' => 'Accra Metropolitan', 'capital' => 'Accra', 'district_type' => 'metropolitan'],
                ['id' => 48, 'region_id' => 2, 'name' => 'Ada East', 'capital' => 'Ada Foah', 'district_type' => 'district'],
                ['id' => 49, 'region_id' => 2, 'name' => 'Ada West', 'capital' => 'Sege', 'district_type' => 'district'],
                ['id' => 50, 'region_id' => 2, 'name' => 'Adenta Municipal', 'capital' => 'Adenta', 'district_type' => 'municipal'],
                ['id' => 51, 'region_id' => 2, 'name' => 'Ashaiman Municipal', 'capital' => 'Ashaiman', 'district_type' => 'municipal'],
                ['id' => 52, 'region_id' => 2, 'name' => 'Ayawaso Central Municipal', 'capital' => 'Kokomlemle', 'district_type' => 'municipal'],
                ['id' => 53, 'region_id' => 2, 'name' => 'Ayawaso East Municipal', 'capital' => 'Nima', 'district_type' => 'municipal'],
                ['id' => 54, 'region_id' => 2, 'name' => 'Ayawaso North Municipal', 'capital' => 'Accra New Town', 'district_type' => 'municipal'],
                ['id' => 55, 'region_id' => 2, 'name' => 'Ayawaso West Municipal', 'capital' => 'Dzorwulu', 'district_type' => 'municipal'],
                ['id' => 56, 'region_id' => 2, 'name' => 'Ga Central Municipal', 'capital' => 'Sowutuom', 'district_type' => 'municipal'],
                ['id' => 57, 'region_id' => 2, 'name' => 'Ga East Municipal', 'capital' => 'Abokobi', 'district_type' => 'municipal'],
                ['id' => 58, 'region_id' => 2, 'name' => 'Ga North Municipal', 'capital' => 'Amomole', 'district_type' => 'municipal'],
                ['id' => 59, 'region_id' => 2, 'name' => 'Ga South Municipal', 'capital' => 'Ngleshie Amanfro', 'district_type' => 'municipal'],
                ['id' => 60, 'region_id' => 2, 'name' => 'Ga West Municipal', 'capital' => 'Amasaman', 'district_type' => 'municipal'],
                ['id' => 61, 'region_id' => 2, 'name' => 'Korle Klottey Municipal', 'capital' => 'Osu', 'district_type' => 'municipal'],
                ['id' => 62, 'region_id' => 2, 'name' => 'Kpone Katamanso Municipal', 'capital' => 'Kpone', 'district_type' => 'municipal'],
                ['id' => 63, 'region_id' => 2, 'name' => 'Krowor Municipal', 'capital' => 'Nungua', 'district_type' => 'municipal'],
                ['id' => 64, 'region_id' => 2, 'name' => 'La Dade Kotopon Municipal', 'capital' => 'La', 'district_type' => 'municipal'],
                ['id' => 65, 'region_id' => 2, 'name' => 'La Nkwantanang Madina Municipal', 'capital' => 'Madina', 'district_type' => 'municipal'],
                ['id' => 66, 'region_id' => 2, 'name' => 'Ledzokuku Municipal', 'capital' => 'Teshie', 'district_type' => 'municipal'],
                ['id' => 67, 'region_id' => 2, 'name' => 'Ningo Prampram', 'capital' => 'Prampram', 'district_type' => 'district'],
                ['id' => 68, 'region_id' => 2, 'name' => 'Okaikwei North Municipal', 'capital' => 'Tesano', 'district_type' => 'municipal'],
                ['id' => 69, 'region_id' => 2, 'name' => 'Shai Osudoku', 'capital' => 'Dodowa', 'district_type' => 'district'],
                ['id' => 70, 'region_id' => 2, 'name' => 'Tema Metropolitan', 'capital' => 'Tema', 'district_type' => 'metropolitan'],
                ['id' => 71, 'region_id' => 2, 'name' => 'Tema West Municipal', 'capital' => 'Tema Community 18', 'district_type' => 'municipal'],
                ['id' => 72, 'region_id' => 2, 'name' => 'Weija Gbawe Municipal', 'capital' => 'Weija', 'district_type' => 'municipal'],
                ['id' => 73, 'region_id' => 3, 'name' => 'Asunafo North Municipal', 'capital' => 'Goaso', 'district_type' => 'municipal'],
                ['id' => 74, 'region_id' => 3, 'name' => 'Asunafo South', 'capital' => 'Kukuom', 'district_type' => 'district'],
                ['id' => 75, 'region_id' => 3, 'name' => 'Asutifi North', 'capital' => 'Kenyasi', 'district_type' => 'district'],
                ['id' => 76, 'region_id' => 3, 'name' => 'Asutifi South', 'capital' => 'Hwidiem', 'district_type' => 'district'],
                ['id' => 77, 'region_id' => 3, 'name' => 'Tano North Municipal', 'capital' => 'Duayaw Nkwanta', 'district_type' => 'municipal'],
                ['id' => 78, 'region_id' => 3, 'name' => 'Tano South Municipal', 'capital' => 'Bechem', 'district_type' => 'municipal'],
                ['id' => 79, 'region_id' => 4, 'name' => 'Banda', 'capital' => 'Banda Ahenkro', 'district_type' => 'district'],
                ['id' => 80, 'region_id' => 4, 'name' => 'Berekum East Municipal', 'capital' => 'Berekum', 'district_type' => 'municipal'],
                ['id' => 81, 'region_id' => 4, 'name' => 'Berekum West', 'capital' => 'Jinijini', 'district_type' => 'district'],
                ['id' => 82, 'region_id' => 4, 'name' => 'Dormaa Central Municipal', 'capital' => 'Dormaa Ahenkro', 'district_type' => 'municipal'],
                ['id' => 83, 'region_id' => 4, 'name' => 'Dormaa East', 'capital' => 'Wamfie', 'district_type' => 'district'],
                ['id' => 84, 'region_id' => 4, 'name' => 'Dormaa West', 'capital' => 'Nkrankwanta', 'district_type' => 'district'],
                ['id' => 85, 'region_id' => 4, 'name' => 'Jaman North', 'capital' => 'Sampa', 'district_type' => 'district'],
                ['id' => 86, 'region_id' => 4, 'name' => 'Jaman South Municipal', 'capital' => 'Drobo', 'district_type' => 'municipal'],
                ['id' => 87, 'region_id' => 4, 'name' => 'Sunyani Municipal', 'capital' => 'Sunyani', 'district_type' => 'municipal'],
                ['id' => 88, 'region_id' => 4, 'name' => 'Sunyani West', 'capital' => 'Odumase', 'district_type' => 'district'],
                ['id' => 89, 'region_id' => 4, 'name' => 'Tain', 'capital' => 'Nsawkaw', 'district_type' => 'district'],
                ['id' => 90, 'region_id' => 4, 'name' => 'Wenchi Municipal', 'capital' => 'Wenchi', 'district_type' => 'municipal'],
                ['id' => 91, 'region_id' => 5, 'name' => 'Atebubu Amantin Municipal', 'capital' => 'Atebubu', 'district_type' => 'municipal'],
                ['id' => 92, 'region_id' => 5, 'name' => 'Kintampo North Municipal', 'capital' => 'Kintampo', 'district_type' => 'municipal'],
                ['id' => 93, 'region_id' => 5, 'name' => 'Kintampo South', 'capital' => 'Jema', 'district_type' => 'district'],
                ['id' => 94, 'region_id' => 5, 'name' => 'Nkoranza North', 'capital' => 'Busunya', 'district_type' => 'district'],
                ['id' => 95, 'region_id' => 5, 'name' => 'Nkoranza South Municipal', 'capital' => 'Nkoranza', 'district_type' => 'municipal'],
                ['id' => 96, 'region_id' => 5, 'name' => 'Pru East', 'capital' => 'Yeji', 'district_type' => 'district'],
                ['id' => 97, 'region_id' => 5, 'name' => 'Pru West', 'capital' => 'Prang', 'district_type' => 'district'],
                ['id' => 98, 'region_id' => 5, 'name' => 'Sene East', 'capital' => 'Kajaji', 'district_type' => 'district'],
                ['id' => 99, 'region_id' => 5, 'name' => 'Sene West Kwame', 'capital' => 'Danso', 'district_type' => 'district'],
                ['id' => 100, 'region_id' => 5, 'name' => 'Techiman Municipal', 'capital' => 'Techiman', 'district_type' => 'municipal'],
                ['id' => 101, 'region_id' => 5, 'name' => 'Techiman North', 'capital' => 'Tuobodom', 'district_type' => 'district'],
                ['id' => 102, 'region_id' => 6, 'name' => 'Abura Asebu Kwamankese', 'capital' => 'Abura Dunkwa', 'district_type' => 'district'],
                ['id' => 103, 'region_id' => 6, 'name' => 'Agona East', 'capital' => 'Nsaba', 'district_type' => 'district'],
                ['id' => 104, 'region_id' => 6, 'name' => 'Agona West Municipal', 'capital' => 'Agona Swedru', 'district_type' => 'municipal'],
                ['id' => 105, 'region_id' => 6, 'name' => 'Ajumako Enyan Essiam', 'capital' => 'Ajumako', 'district_type' => 'district'],
                ['id' => 106, 'region_id' => 6, 'name' => 'Asikuma Odoben Brakwa', 'capital' => 'Breman Asikuma', 'district_type' => 'district'],
                ['id' => 107, 'region_id' => 6, 'name' => 'Assin Central Municipal', 'capital' => 'Assin Foso', 'district_type' => 'municipal'],
                ['id' => 108, 'region_id' => 6, 'name' => 'Assin North', 'capital' => 'Assin Bereku', 'district_type' => 'district'],
                ['id' => 109, 'region_id' => 6, 'name' => 'Assin South', 'capital' => 'Nsuaem Kyekyewere', 'district_type' => 'district'],
                ['id' => 110, 'region_id' => 6, 'name' => 'Awutu Senya East Municipal', 'capital' => 'Kasoa', 'district_type' => 'municipal'],
                ['id' => 111, 'region_id' => 6, 'name' => 'Awutu Senya West', 'capital' => 'Awutu Breku', 'district_type' => 'district'],
                ['id' => 112, 'region_id' => 6, 'name' => 'Cape Coast Metropolitan ', 'capital' => 'Cape Coast', 'district_type' => 'metropolitan'],
                ['id' => 113, 'region_id' => 6, 'name' => 'Effutu Municipal', 'capital' => 'Winneba', 'district_type' => 'municipal'],
                ['id' => 114, 'region_id' => 6, 'name' => 'Ekumfi', 'capital' => 'Esakyir', 'district_type' => 'district'],
                ['id' => 115, 'region_id' => 6, 'name' => 'Gomoa East', 'capital' => 'Potsin', 'district_type' => 'district'],
                ['id' => 116, 'region_id' => 6, 'name' => 'Gomoa Central', 'capital' => 'Afransi', 'district_type' => 'district'],
                ['id' => 117, 'region_id' => 6, 'name' => 'Gomoa West', 'capital' => 'Apam', 'district_type' => 'district'],
                ['id' => 118, 'region_id' => 6, 'name' => 'Komenda Edina Eguafo Abirem Municipal', 'capital' => 'Elmina', 'district_type' => 'municipal'],
                ['id' => 119, 'region_id' => 6, 'name' => 'Mfantsiman Municipal', 'capital' => 'Saltpond', 'district_type' => 'municipal'],
                ['id' => 120, 'region_id' => 6, 'name' => 'Twifo Atti Morkwa Twifo', 'capital' => 'Praso', 'district_type' => 'district'],
                ['id' => 121, 'region_id' => 6, 'name' => 'Twifo Hemang Lower Denkyira', 'capital' => 'Hemang', 'district_type' => 'district'],
                ['id' => 122, 'region_id' => 6, 'name' => 'Upper Denkyira East Municipal', 'capital' => 'Dunkwa on Offin', 'district_type' => 'municipal'],
                ['id' => 123, 'region_id' => 6, 'name' => 'Upper Denkyira West', 'capital' => 'Diaso', 'district_type' => 'district'],
                // ...continue for all other entries using the same logic
            ]
        );
    }
}
