<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OfficeUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('office_unit')->insert([
            ['office_id' => 1, 'unit_id' => 1],
            ['office_id' => 1, 'unit_id' => 2],
            ['office_id' => 1, 'unit_id' => 3],
            ['office_id' => 1, 'unit_id' => 4],
            ['office_id' => 1, 'unit_id' => 5],
            ['office_id' => 1, 'unit_id' => 6],
            ['office_id' => 1, 'unit_id' => 7],
            ['office_id' => 1, 'unit_id' => 8],
            ['office_id' => 1, 'unit_id' => 9],
            ['office_id' => 1, 'unit_id' => 10],
            ['office_id' => 1, 'unit_id' => 11],
            ['office_id' => 1, 'unit_id' => 13],
            ['office_id' => 1, 'unit_id' => 26],
            ['office_id' => 1, 'unit_id' => 37],
            ['office_id' => 1, 'unit_id' => 45],
            ['office_id' => 1, 'unit_id' => 67],
            ['office_id' => 1, 'unit_id' => 68],
            ['office_id' => 1, 'unit_id' => 71],
            ['office_id' => 1, 'unit_id' => 73],
            ['office_id' => 1, 'unit_id' => 84],
            ['office_id' => 1, 'unit_id' => 85],
            ['office_id' => 1, 'unit_id' => 88],
            ['office_id' => 1, 'unit_id' => 89],
            ['office_id' => 1, 'unit_id' => 91],
            ['office_id' => 1, 'unit_id' => 135],
            ['office_id' => 1, 'unit_id' => 137],
            ['office_id' => 1, 'unit_id' => 155],
            ['office_id' => 1, 'unit_id' => 166],
            ['office_id' => 1, 'unit_id' => 167],
            ['office_id' => 1, 'unit_id' => 170],
            ['office_id' => 1, 'unit_id' => 183],
            ['office_id' => 1, 'unit_id' => 187],
            ['office_id' => 1, 'unit_id' => 188],
            ['office_id' => 1, 'unit_id' => 190],
            ['office_id' => 1, 'unit_id' => 11],
            ['office_id' => 1, 'unit_id' => 13],
            ['office_id' => 1, 'unit_id' => 37],
            ['office_id' => 1, 'unit_id' => 45],
            ['office_id' => 1, 'unit_id' => 67],
            ['office_id' => 1, 'unit_id' => 68],
            ['office_id' => 1, 'unit_id' => 71],
            ['office_id' => 1, 'unit_id' => 73],
            ['office_id' => 1, 'unit_id' => 84],
            ['office_id' => 1, 'unit_id' => 85],
            ['office_id' => 1, 'unit_id' => 88],
            ['office_id' => 1, 'unit_id' => 89],
            ['office_id' => 1, 'unit_id' => 91],
            ['office_id' => 1, 'unit_id' => 135],
            ['office_id' => 1, 'unit_id' => 137],
            ['office_id' => 1, 'unit_id' => 155],
            ['office_id' => 1, 'unit_id' => 166],
            ['office_id' => 1, 'unit_id' => 167],
            ['office_id' => 1, 'unit_id' => 170],
            ['office_id' => 1, 'unit_id' => 183],
            ['office_id' => 1, 'unit_id' => 187],
            ['office_id' => 1, 'unit_id' => 188],
            ['office_id' => 1, 'unit_id' => 190],
            ['office_id' => 1, 'unit_id' => 29],
            ['office_id' => 1, 'unit_id' => 38],
            ['office_id' => 1, 'unit_id' => 53],
            ['office_id' => 1, 'unit_id' => 74],
            ['office_id' => 1, 'unit_id' => 75],
            ['office_id' => 1, 'unit_id' => 76],
            ['office_id' => 1, 'unit_id' => 78],
            ['office_id' => 1, 'unit_id' => 96],
            ['office_id' => 1, 'unit_id' => 119],
            ['office_id' => 1, 'unit_id' => 120],
            ['office_id' => 1, 'unit_id' => 125],
            ['office_id' => 1, 'unit_id' => 139],
            ['office_id' => 1, 'unit_id' => 143],
            ['office_id' => 1, 'unit_id' => 154],
            ['office_id' => 1, 'unit_id' => 158],
            // ['office_id' => 1, 'unit_id' => 249], // this unit does not exists in development
            ['office_id' => 1, 'unit_id' => 30],
            ['office_id' => 1, 'unit_id' => 31],
            ['office_id' => 1, 'unit_id' => 32],
            ['office_id' => 1, 'unit_id' => 33],
            ['office_id' => 1, 'unit_id' => 34],
            ['office_id' => 1, 'unit_id' => 35],
            ['office_id' => 1, 'unit_id' => 36],
            ['office_id' => 1, 'unit_id' => 40],
            ['office_id' => 1, 'unit_id' => 41],
            ['office_id' => 1, 'unit_id' => 39],
            ['office_id' => 1, 'unit_id' => 42],
            ['office_id' => 1, 'unit_id' => 44],
            ['office_id' => 1, 'unit_id' => 50],
            ['office_id' => 1, 'unit_id' => 51],
            ['office_id' => 1, 'unit_id' => 59],
            ['office_id' => 1, 'unit_id' => 61],
            ['office_id' => 1, 'unit_id' => 60],
            ['office_id' => 1, 'unit_id' => 62],
            ['office_id' => 1, 'unit_id' => 64],
            ['office_id' => 1, 'unit_id' => 69],
            ['office_id' => 1, 'unit_id' => 70],
            ['office_id' => 1, 'unit_id' => 92],
            ['office_id' => 1, 'unit_id' => 136],
            ['office_id' => 1, 'unit_id' => 149],
            ['office_id' => 1, 'unit_id' => 191],
            ['office_id' => 1, 'unit_id' => 192],
            ['office_id' => 1, 'unit_id' => 193],
            ['office_id' => 1, 'unit_id' => 194],
            ['office_id' => 1, 'unit_id' => 195],
            ['office_id' => 1, 'unit_id' => 196],
            ['office_id' => 1, 'unit_id' => 250],
            ['office_id' => 1, 'unit_id' => 90],
            ['office_id' => 2, 'unit_id' => 134],
            ['office_id' => 1, 'unit_id' => 152],
            ['office_id' => 1, 'unit_id' => 153],
            ['office_id' => 5, 'unit_id' => 43],
            ['office_id' => 3, 'unit_id' => 197],
            ['office_id' => 6, 'unit_id' => 198],
            ['office_id' => 5, 'unit_id' => 199],
            ['office_id' => 8, 'unit_id' => 200],
            ['office_id' => 9, 'unit_id' => 201],
            ['office_id' => 7, 'unit_id' => 202],
            ['office_id' => 4, 'unit_id' => 203],
            ['office_id' => 17, 'unit_id' => 205],
            ['office_id' => 16, 'unit_id' => 206],
            ['office_id' => 18, 'unit_id' => 207],
            ['office_id' => 11, 'unit_id' => 208],
            ['office_id' => 10, 'unit_id' => 209],
            ['office_id' => 13, 'unit_id' => 210],
            ['office_id' => 14, 'unit_id' => 211],
            ['office_id' => 15, 'unit_id' => 212],
            ['office_id' => 12, 'unit_id' => 213],
            ['office_id' => 66, 'unit_id' => 48],
            // ['office_id' => 1, 'unit_id' => 248],
            ['office_id' => 26, 'unit_id' => 14],
            ['office_id' => 40, 'unit_id' => 18],
            ['office_id' => 35, 'unit_id' => 57],
            ['office_id' => 25, 'unit_id' => 110],
            ['office_id' => 37, 'unit_id' => 127],
            ['office_id' => 42, 'unit_id' => 128],
            // ['office_id' => 1, 'unit_id' => 144], //Saema district could not find district
            ['office_id' => 65, 'unit_id' => 176],
            ['office_id' => 6, 'unit_id' => 177],
            ['office_id' => 22, 'unit_id' => 178],

        ]);
    }
}
