<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@yield('title', 'Qualification Report')</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #222; }
        h1 { font-size: 16px; margin: 0 0 4px; }
        .meta { color: #666; font-size: 9px; margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; font-size: 9px; text-transform: uppercase; letter-spacing: 0.03em; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 8px; color: #888; text-align: center; }
        .filter-summary { background: #f9fafb; border: 1px solid #e5e7eb; padding: 6px 8px; margin-bottom: 10px; font-size: 9px; }
        .bar { display: inline-block; height: 8px; background: #4f46e5; vertical-align: middle; }
    </style>
</head>
<body>
    <h1>@yield('title', 'Qualification Report')</h1>
    <div class="meta">
        Generated: {{ now()->format('Y-m-d H:i') }}
        @isset($user) &middot; By: {{ $user->name ?? '' }} @endisset
    </div>

    @isset($filterSummary)
        <div class="filter-summary"><strong>Filters:</strong> {{ $filterSummary }}</div>
    @endisset

    @yield('content')

    <div class="footer">
        Generated by HRMIS &middot; {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
